version: '3'
services:
  mongo:
    image: mongo:5
    restart: always
    logging:
      driver: none
    ports:
      - 27017:27017

  dev:
    depends_on:
      - mongo
    restart: on-failure
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - '7070:7070'
    environment:
      - NODE_ENV=container
      - PORT=7070
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'start']

  test:
    depends_on:
      - mongo
    restart: 'no'
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:3000'
    environment:
      - NODE_ENV=container
      - PORT=3000
    volumes:
      - /app/node_modules
      - .:/app
    command: npm test
      # sh -cx "npm test"
      