version: '3'
services:
  mongo:
    image: mongo:6
    restart: on-failure
    logging:
      driver: none
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  dev:
    depends_on:
      - mongo
    restart: on-failure
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - '7070:7070'
    environment:
      - NODE_ENV=development
      - PORT=7070
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'start']

  test:
    depends_on:
      - mongo
    restart: 'no'
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:3000'
    environment:
      - NODE_ENV=container
      - PORT=3000
    volumes:
      - /app/node_modules
      - .:/app
    command: npm test
      # sh -cx "npm test"
      