version: '3'
services:
  dev:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - '6000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'start']
  test:
    build:  
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    # command: ['npm', 'test']    